ptf_rename_vars <- function(df) {
  dplyr::rename(
    df,

    # ---- Metadatos/EC5 (conservo nombres útiles tal cual) ----
    ec5_uuid = `ec5_uuid`,
    created_at = `created_at`,
    uploaded_at = `uploaded_at`,
    created_by = `created_by`,
    title = `title`,

    # ---- Inicio y datos básicos ----
    inicio = `1_Inicie`,
    nombre = `2_1_Cmo_es_su_nombre`,

    # ---- Coordenadas (Q3 autorización -> campos de coord) ----
    latitud = `lat_3_2_Autoriza_a_que_r`,
    longitud = `long_3_2_Autoriza_a_que_r`,
    precision_metros = `accuracy_3_2_Autoriza_a_que_r`,
    norte = `UTM_Northing_3_2_Autoriza_a_que_r`,
    este = `UTM_Easting_3_2_Autoriza_a_que_r`,
    zona = `UTM_Zone_3_2_Autoriza_a_que_r`,

    # ---- Demografía / identidad ----
    edad = `4_3_Cuntos_aos_cumpl`,
    sexo = `5_4_Sexo_sexo_asigna`,
    orientacion_sexual = `6_6_Usted_siente_atr`,
    orientacion_sexual_otro_txt = `8_Otro_cul`,
    orientacion_sexual_otro_voz = `9_Otro_cul`,
    identidad_genero = `10_7_Usted_se_recono`,
    identidad_genero_otro_txt = `12_Otro_cul`,
    identidad_genero_otro_voz = `13_Otro_cul`,
    etnia = `14_8_De_acuerdo_con_`,
    alfabetismo = `15_9_Sabe_leer_y_esc`,
    educacion = `16_10_Cul_es_el_nive`,

    # ---- Funcionalidad / discapacidad ----
    oir = `17_11_Or_an_usando_a`,
    oir_causa = `18_111_Or_an_usando_`,
    hablar = `19_12_Hablar_o_conve`,
    hablar_causa = `20_121_Hablar_o_conv`,
    ver = `21_13_Ver_an_usando_`,
    ver_causa = `22_131_Ver_an_usando`,
    moverse = `23_14_Mover_el_cuerp`,
    moverse_causa = `24_141_Mover_el_cuer`,
    manos = `25_15_Agarrar_o_move`,
    manos_causa = `26_151_Agarrar_o_mov`,
    cognitiva = `27_16_Entender_apren`,
    cognitiva_causa = `28_161_Entender_apre`,
    autocuidado = `29_17_Comer_vestirse`,
    autocuidado_causa = `30_171_Comer_vestirs`,
    interaccion = `31_18_Relacionarse_o`,
    interaccion_causa = `32_181_Relacionarse_`,
    afectacion_conflicto = `33_19_Usted_o_algn_m`,
    afectacion_otro_1 = `35_Otro_cul`,
    afectacion_otro_2 = `36_Otro_cul`,
    afiliado_riesgos_laborales = `37_20_Est_afiliadoa_`,
    cotiza_pension = `38_21_Est_cotizando_`,
    afiliado_salud = `39_22_Est_afiliadoa_`,
    regimen_salud = `40_23_A_cul_de_los_s`,
    actividad_semana = `41_24_En_qu_activida`,
    actividad_paga_semana = `42_25_Adems_de_lo_an`,
    tenia_trabajo_semana = `43_26_Aunque_no_trab`,
    trabajo_no_remunerado_semana = `44_27_Trabaj_LA_SEMA`,
    busco_trabajo_4_semanas = `45_28_En_las_LTIMAS_`,
    quiere_trabajo = `46_29_Desea_consegui`,
    trabajo_12_meses = `47_30_Durante_los_lt`,
    busco_despues_ultimo_empleo = `48_31_Despus_de_su_l`,
    busco_12_meses = `49_32_Durante_los_lt`,
    disponible_semana = `50_33_Si_le_hubiera_`,
    ocupacion_desc_1 = `52_Qu_hace_en_este_t`,
    ocupacion_desc_2 = `53_Qu_hace_en_este_t`,
    ingreso_principal = `54_35_Cunto_gan_el_M`,
    otros_trabajos = `55_36_Adems_de_su_oc`,
    otros_trabajos_cuales_1 = `57_Otro_cul`,
    otros_trabajos_cuales_2 = `58_Otro_cul`,
    ingreso_otros = `59_37_Cunto_gan_el_M`,
    ingreso_persona = `60_38_Cul_es_el_tota`,
    ingreso_hogar = `61_39_Cul_es_el_tota`,
    ingresos_alcance = `62_40_Los_ingresos_d`,
    gasto_alimentos = `63_41_Cunto_gast_su_`,
    alimentos_sin_compra = `64_42_Durante_el_PAS`,
    alimentos_sin_compra_valor = `65_43_En_cunto_estim`,
    alimentos_sin_compra_origen = `66_44_Cmo_obtuvieron`,
    ayudas_gobierno = `67_45_Durante_los_lt`,
    ayudas_gobierno_otro_1 = `69_Otro_cul`,
    ayudas_gobierno_otro_2 = `70_Otro_cul`,
    ayudas_no_gubernamentales = `71_46_Durante_los_lt`,
    ayudas_no_gub_cuales_1 = `73_Otro_cul`,
    ayudas_no_gub_cuales_2 = `74_Otro_cul`,
    pertenencia_organizaciones = `75_47_Pertenece_a_al`,
    contacto_organizaciones = `76_48_En_el_ltimo_ao`,
    liderazgo_organizaciones = `77_49_Usted_lidera_p`,
    respeto_inclusion_puntaje = `78_50_Indique_su_niv`,
    discriminacion_motivos = `79_51_Durante_el_PRE`,
    trabajos_mujeres_puntaje = `80_52_Indique_su_niv`,
    amistad_otras_etnias_puntaje = `81_53_Indique_su_niv`,
    trabajar_con_discapacidad_puntaje = `82_54_Indique_su_niv`,
    importancia_familia_puntaje = `84_Familia`,
    importancia_amistades_puntaje = `85_Amistades`,
    importancia_tiempo_libre_puntaje = `86_El_tiempo_libre`,
    importancia_trabajo_puntaje = `87_El_trabajo`,
    importancia_religion_puntaje = `88_La_religin`,
    importancia_politica_puntaje = `89_La_poltica`,
    confianza_familia_puntaje = `91_Familia`,
    confianza_colegas_puntaje = `92_Colegas_de_trabaj`,
    confianza_desconocidos_puntaje = `93_Personas_desconoc`,
    confianza_vecinos_puntaje = `94_Vecinosas`,
    confianza_amistades_puntaje = `95_Amistades`,
    confianza_comunidad_puntaje = `96_Otras_personas_de`,
    confianza_otra_nacionalidad_puntaje = `97_Personas_de_otra_`,
    no_quisiera_vecino = `98_57_De_las_siguien`,
    num_visitas_frecuentes = `99_58_Cuntas_persona`,
    num_apoyos_busqueda = `100_59_Cuntas_person`,
    organizarse_facilidad_puntaje = `101_60_En_una_escala`,
    intermedio = `102_Contine`,
  )
}


ptf_rename_vars_siviru <- function(df) {
  dplyr::rename(
    df,
    espacio_cultivo = `103_61_Usted_o_algn_`,
    cultivo_frutas_cultiva = `105_Cultiva`,
    cultivo_frutas_cuales = `106_Cules`,
    cultivo_frutas_consumo = `107_De_lo_que_se_cul`,
    cultivo_frutas_frecuencia = `108_Con_qu_frecuenci`,
    cultivo_cereales_cultiva = `110_Cultiva`,
    cultivo_cereales_cuales = `111_Cules`,
    cultivo_cereales_consumo = `112_De_lo_que_se_cul`,
    cultivo_cereales_frecuencia = `113_Con_qu_frecuenci`,
    cultivo_raices_tuberculos_cultiva = `115_Cultiva`,
    cultivo_raices_tuberculos_cuales = `116_Cules`,
    cultivo_raices_tuberculos_consumo = `117_De_lo_que_se_cul`,
    cultivo_raices_tuberculos_frecuencia = `118_Con_qu_frecuenci`,
    cultivo_platanos_cultiva = `120_Cultiva`,
    cultivo_platanos_cuales = `121_Cules`,
    cultivo_platanos_consumo = `122_De_lo_que_se_cul`,
    cultivo_platanos_frecuencia = `123_Con_qu_frecuenci`,
    cultivo_verduras_hortalizas_cultiva = `125_Cultiva`,
    cultivo_verduras_hortalizas_cuales = `126_Cules`,
    cultivo_verduras_hortalizas_consumo = `127_De_lo_que_se_cul`,
    cultivo_verduras_hortalizas_frecuencia = `128_Con_qu_frecuenci`,
    cultivo_leguminosas_cultiva = `130_Cultiva`,
    cultivo_leguminosas_cuales = `131_Cules`,
    cultivo_leguminosas_consumo = `132_De_lo_que_se_cul`,
    cultivo_leguminosas_frecuencia = `133_Con_qu_frecuenci`,
    cultivo_semillas_frutos_secos_cultiva = `135_Cultiva`,
    cultivo_semillas_frutos_secos_cuales = `136_Cules`,
    cultivo_semillas_frutos_secos_consumo = `137_De_lo_que_se_cul`,
    cultivo_semillas_frutos_secos_frecuencia = `138_Con_qu_frecuenci`,
    cultivo_otros_cultiva = `140_Cultiva`,
    cultivo_otros_cuales = `141_Cules`,
    cultivo_otros_consumo = `142_De_lo_que_se_cul`,
    cultivo_otros_frecuencia = `143_Con_qu_frecuenci`,
    otras_formas_alimentos = `144_62_Usted_o_algn_`,
    pesca_hace = `146_Se_realiza_esta_`,
    pesca_frecuencia = `147_Con_qu_frecuenci`,
    pesca_alimentos = `148_Qu_alimentos_obt`,
    caza_hace = `150_Se_realiza_esta_`,
    caza_frecuencia = `151_Con_qu_frecuenci`,
    caza_alimentos = `152_Qu_alimentos_obt`,
    recoleccion_hace = `154_Se_realiza_esta_`,
    recoleccion_frecuencia = `155_Con_qu_frecuenci`,
    recoleccion_alimentos = `156_Qu_alimentos_obt`,
    trueque_hace = `158_Se_realiza_esta_`,
    trueque_frecuencia = `159_Con_qu_frecuenci`,
    trueque_alimentos = `160_Qu_alimentos_obt`,
    donacion_hace = `162_Se_realiza_esta_`,
    donacion_frecuencia = `163_Con_qu_frecuenci`,
    donacion_alimentos = `164_Qu_alimentos_obt`,
    preocupacion_alimentos = `166_Se_preocup_por_n`,
    sin_saludables = `167_No_pudo_comer_al`,
    poca_variedad = `168_Consumi_poca_var`,
    salto_comida = `169_Tuvo_que_saltar_`,
    comio_menos = `170_Comi_menos_de_lo`,
    sin_alimentos = `171_El_hogar_se_qued`,
    hambre_no_comio = `172_Tuvo_hambre_pero`,
    dia_sin_comer = `173_No_comi_en_un_da`,
    familiar_azoteas = `174_64_Est_familiari`,
    que_sabe_azoteas = `176_Cunteme_brevemen`,
    verificar_azoteas = `177_Verificar`,
    como_aprendio_azoteas = `178_66_Cmo_lleg_a_fa`,
    como_aprendio_azoteas_otro_1 = `180_Cmo_lleg_a_famil`,
    como_aprendio_azoteas_otro_2 = `181_Cmo_lleg_a_famil`,
    cultivo_azotea_actual = `182_67_Actualmente_e`,
    cultivo_azotea_tipo = `183_68_Qu_tipo_de_cu`,
    cultivo_azotea_otro_1 = `185_Otro_tipo_de_cul`,
    cultivo_azotea_otro_2 = `186_Otro_tipo_de_cul`,
    cultivo_azotea_hace_un_ano = `187_69_Hace_un_ao_re`,
    uso_medicinal_frecuencia = `188_70_Con_qu_frecue`,
    uso_alimentario_frecuencia = `189_71_Con_qu_frecue`,
    beneficia = `190_72_La_persona_es`,
    satisfaccion_general_puntaje = `191_73_Cmo_describir`,
    herramientas_satisfaccion_puntaje = `193_Satisfaccin_Cmo_`,
    herramientas_importancia_puntaje = `194_Importancia_Qu_t`,
    herramientas_utilidad_puntaje = `195_Utilidad_Qu_tan_`,
    semillas_satisfaccion_puntaje = `197_Satisfaccin_Cmo_`,
    semillas_importancia_puntaje = `198_Importancia_Qu_t`,
    semillas_utilidad_puntaje = `199_Utilidad_Qu_tan_`,
    formacion_genero_satisfaccion_puntaje = `201_Satisfaccin_Cmo_`,
    formacion_genero_importancia_puntaje = `202_Importancia_Qu_t`,
    formacion_genero_utilidad_puntaje = `203_Utilidad_Qu_tan_`,
    formacion_derechos_satisfaccion_puntaje = `205_Satisfaccin_Cmo_`,
    formacion_derechos_importancia_puntaje = `206_Importancia_Qu_t`,
    formacion_derechos_utilidad_puntaje = `207_Utilidad_Qu_tan_`,
    formacion_proyecto_vida_satisfaccion_puntaje = `209_Satisfaccin_Cmo_`,
    formacion_proyecto_vida_importancia_puntaje = `210_Importancia_Qu_t`,
    formacion_proyecto_vida_utilidad_puntaje = `211_Utilidad_Qu_tan_`,
    formacion_construccion_satisfaccion_puntaje = `213_Satisfaccin_Cmo_`,
    formacion_construccion_importancia_puntaje = `214_Importancia_Qu_t`,
    formacion_construccion_utilidad_puntaje = `215_Utilidad_Qu_tan_`,
    formacion_conocimientos_satisfaccion_puntaje = `217_Satisfaccin_Cmo_`,
    formacion_conocimientos_importancia_puntaje = `218_Importancia_Qu_t`,
    formacion_conocimientos_utilidad_puntaje = `219_Utilidad_Qu_tan_`,
    formacion_comercializacion_satisfaccion_puntaje = `221_Satisfaccin_Cmo_`,
    formacion_comercializacion_importancia_puntaje = `222_Importancia_Qu_t`,
    formacion_comercializacion_utilidad_puntaje = `223_Utilidad_Qu_tan_`,
    lo_mejor_1 = `225_Respuesta_abiert`,
    lo_mejor_2 = `226_Respuesta_abiert`,
    mejoras_1 = `228_Respuesta_abiert`,
    mejoras_2 = `229_Respuesta_abiert`,
    autoriza_contacto = `231_Nos_autoriza_a_c`,
    telefono = `232_Nmero_de_telfono`,
    final = `233_Finalice`
  )
}
