project:
  type: book
  pre-render: pre-render.R
  # post-render: post-render.R
  output-dir: _book
  execute-dir: project

execute:
  echo: false    # hide code globally (show results only)
  warning: false # optional
  message: false # optional
  freeze: auto  # re-render only when source changes

book:
  title: "quartobook"
  author: "VCA"
  chapters:
    - index.qmd
    - siviru.qmd
    - siviru_caracteriza.qmd
    - usaraga_caracteriza.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - Annex/entries_count.qmd
    - Annex/survey_times.qmd
    - Annex/abridge.qmd


bibliography: references.bib

format:
  html:
    embed-resources: false
    theme:
      - cosmo
      - brand
    lightbox: true
    resources: _book
  # pdf:
  #   documentclass: scrreprt
  # docx:
  #   toc: true
  #   number-sections: true


