project:
  type: book
  output-dir: _book
  execute-dir: project
  # pre-render: pre-render.R
  # post-render: post-render.R

execute:
  echo: false    # hide code globally (show results only)
  warning: false # optional
  message: false # optional
  freeze: auto  # re-render only when source changes

book:
  title: "Evaluación PTF"
  author: "VCA"
  # downloads: [pdf, epub, docx] # just put the links; make sure to render
  chapters:
    - index.qmd
    - part: "Caracterización de beneficiarias y beneficiarios"
      chapters:
      - caracteriza_siviru.qmd
      - caracteriza_usaraga.qmd
      - caracteriza_sirenas.qmd
    - part: "Comparación entre grupos"
      chapters:
        - compare_siviru.qmd
        - compare_usaraga.qmd
        - compare_sirenas.qmd
        - compare_saija.qmd
        - compare_acapa.qmd
        - compare_raices.qmd
        - compare_mariposas.qmd
        - compare_asogesampa.qmd
    - references.qmd
  appendices:
    - Annex/entries_count.qmd
    - Annex/survey_times.qmd
    - Annex/abridge.qmd


bibliography: references.bib

format:
  html:
    embed-resources: false
    theme:
      - cosmo
      - brand
    lightbox: true
    resources: _book
  # pdf:
  #   documentclass: scrreprt
  # docx:
  #   toc: true
  #   number-sections: true


